language: node_js
node_js:
  - "0.10"
deploy:
  provider: heroku
  api_key:
    secure: b23MfUOoyMSGrG6MaBi50jjKNkt3Gmtm7H217UtZNnFKSE499dHU6S1j5tjn/F7qDcEVHbjlc45XID1LIBxsq9m1sri2rxTO/l/8M9mrgMJcS9K1akQ5MHuvQ0LtJ7w/egn0XwUBcKLa0VCAHdRJ6Cr+mITTwPHaNVUEB3pBDdI=
  app: purecss-stage
